//*****************************************************************************
// Copyright (c) 2013 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.2
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "Mame_pins.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"

//*****************************************************************************
void
PortFunctionInit(void)
{
	 //
	// Enable Peripheral Clocks
	//
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_QEI0);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_QEI1);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOC);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
	MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);


	//Enabe P1 Joystick
	MAP_GPIOPinTypeGPIOInput(GPIO_JOY1_BASE, GPIO_JOY1_UP | GPIO_JOY1_DOWN | GPIO_JOY1_RIGHT | GPIO_JOY1_LEFT );
	MAP_GPIOPadConfigSet(GPIO_JOY1_BASE, GPIO_JOY1_UP | GPIO_JOY1_DOWN | GPIO_JOY1_RIGHT | GPIO_JOY1_LEFT, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);

	//Enable P1 Buttons
	MAP_GPIOPinTypeGPIOInput(GPIO_P1_BASE, GPIO_P1_A | GPIO_P1_B | GPIO_P1_C | GPIO_P1_D | GPIO_P1_E | GPIO_P1_F | GPIO_P1_START | GPIO_P1_COIN);
	MAP_GPIOPadConfigSet(GPIO_P1_BASE, GPIO_P1_A | GPIO_P1_B | GPIO_P1_C | GPIO_P1_D | GPIO_P1_E | GPIO_P1_F | GPIO_P1_START | GPIO_P1_COIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);

	// Enable Output Status Light
	MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE,GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3);

	// Trackball X Axis
	// First open the lock and select the bits we want to modify in the GPIO commit register.
	// Then modify the configuration of the pins that we unlocked.
	HWREG(GPIO_PORTD_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
	HWREG(GPIO_PORTD_BASE + GPIO_O_CR) = 0x80;
	MAP_GPIOPinConfigure(GPIO_TRK_X_A_QEI);
	MAP_GPIOPinTypeQEI(GPIO_TRK_X_BASE, GPIO_TRK_X_A);
	MAP_GPIOPinConfigure(GPIO_TRK_X_B_QEI);
	MAP_GPIOPinTypeQEI(GPIO_TRK_X_BASE, GPIO_TRK_X_B);

	// Trackball Y Axis
	MAP_GPIOPinConfigure(GPIO_TRK_Y_A_QEI);
	MAP_GPIOPinTypeQEI(GPIO_TRK_Y_BASE,  GPIO_TRK_Y_A);
	MAP_GPIOPinConfigure(GPIO_PC6_PHB1);
	MAP_GPIOPinTypeQEI(GPIO_TRK_Y_BASE,  GPIO_TRK_Y_B);

	//
	// Enable port PD4/5 for USB0 USB0DP
	//
	MAP_GPIOPinTypeUSBAnalog(GPIO_PORTD_BASE, GPIO_PIN_5);
	MAP_GPIOPinTypeUSBAnalog(GPIO_PORTD_BASE, GPIO_PIN_4);

}
